import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:logging/logging.dart';

// Import tables
import 'tables.dart';
import 'daos/card_dao.dart';
import 'daos/search_dao.dart';

// Generated by drift_dev when running `dart run build_runner build`
part 'app_database.g.dart';

@DriftDatabase(
  tables: [
    Tasks,
    KvStore,
    AgentActivityMessages,
    CardCache,
    SystemActions,
    ClarificationRequests,
    PersonaChatMessages
  ],
  daos: [CardDao],
)
class AppDatabase extends _$AppDatabase {
  final Logger _logger = Logger('AppDatabase');

  /// Lazy-initialized SearchDao for FTS5 full-text search.
  late final SearchDao searchDao = SearchDao(this);

  /// Singleton pattern to ensure one DB connection
  static AppDatabase?
      _instance; // We will treat the current opened DB as singleton for the app lifecycle
  static AppDatabase get instance {
    if (_instance == null) {
      throw Exception(
          'Database not initialized. Call AppDatabase.init(userId) first.');
    }
    return _instance!;
  }

  static bool get isInitialized => _instance != null;

  /// Initialize the database for a specific user
  static Future<void> init(String userId) async {
    if (_instance != null) {
      await _instance!.close();
      _instance = null;
    }

    _instance = AppDatabase._(userId);
  }

  /// Private constructor
  AppDatabase._(String userId) : super(_openConnection(userId));

  @override
  int get schemaVersion => 11;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (Migrator m) async {
          await m.createAll();
          // Create indices
          await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status)');
          await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_tasks_scheduled_at ON tasks(scheduled_at)');
          await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_tasks_type_biz_id ON tasks(type, biz_id)');
          await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_kv_bucket ON kv_store(bucket)');
          await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_card_cache_timestamp ON card_cache(timestamp)');
          await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_system_actions_status ON system_actions(status)');
          await _createClarificationRequestIndices();
          // Create FTS5 virtual tables for full-text search
          await searchDao.createFtsTables();
        },
        onUpgrade: (Migrator m, int from, int to) async {
          if (from < 2) {
            await m.createTable(agentActivityMessages);
          }
          // Only add agent_id column if upgrading from version 2 to 3
          // If upgrading from version 1, the table was just created with all columns including agent_id
          if (from == 2 && to >= 3) {
            // Try to add the column, but ignore if it already exists
            try {
              await m.addColumn(
                  agentActivityMessages, agentActivityMessages.agentId);
            } catch (e) {
              // If column already exists (duplicate column error), ignore it
              final errorStr = e.toString().toLowerCase();
              if (errorStr.contains('duplicate column') ||
                  (errorStr.contains('sqlite') &&
                      errorStr.contains('agent_id'))) {
                _logger
                    .info('agent_id column already exists, skipping migration');
              } else {
                // Re-throw if it's a different error
                rethrow;
              }
            }
          }
          if (from < 4) {
            try {
              await m.addColumn(tasks, tasks.dependencies);
            } catch (e) {
              _logger.info(
                  'dependencies column might already exist, skipping: $e');
            }
          }
          if (from < 5) {
            await m.createTable(cardCache);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_card_cache_timestamp ON card_cache(timestamp)');
          }
          if (from < 7) {
            await m.createTable(systemActions);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_system_actions_status ON system_actions(status)');
          }
          if (from < 8) {
            try {
              await customStatement(
                  'ALTER TABLE card_cache DROP COLUMN is_draft');
            } catch (e) {
              _logger
                  .info('is_draft column may not exist or already dropped: $e');
            }
          }
          if (from < 9) {
            await m.createTable(personaChatMessages);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_persona_chat_character ON persona_chat_messages(character_id)');
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_persona_chat_unread ON persona_chat_messages(character_id, is_read)');
          }
          if (from < 10) {
            // Create FTS5 virtual tables for full-text search
            await searchDao.createFtsTables();
          }
          if (from < 11) {
            await _createClarificationRequestsTable(m);
          }
        },
      );

  Future<void> _createClarificationRequestsTable(Migrator m) async {
    try {
      await m.createTable(clarificationRequests);
    } catch (e) {
      if (_isAlreadyExistsError(e, 'clarification_requests')) {
        _logger.info(
            'clarification_requests table already exists, skipping migration');
      } else {
        rethrow;
      }
    }
    await _createClarificationRequestIndices();
  }

  Future<void> _createClarificationRequestIndices() async {
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_clarification_requests_status ON clarification_requests(status)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_clarification_requests_fact_id ON clarification_requests(fact_id)');
    await customStatement(
        'CREATE INDEX IF NOT EXISTS idx_clarification_requests_dedupe ON clarification_requests(dedupe_key)');
  }

  bool _isAlreadyExistsError(Object error, String tableName) {
    final errorStr = error.toString().toLowerCase();
    return errorStr.contains(tableName) &&
        (errorStr.contains('already exists') ||
            errorStr.contains('duplicate table'));
  }
}

/// Opens the connection using drift_flutter
QueryExecutor _openConnection(String userId) {
  final dbName = 'memex_local_$userId';

  return driftDatabase(name: dbName);
}
